ywmoyue/biliuwp-lite

- src/BiliLite.UWP/Modules/Detail/LiveRoomVM.cs
Fixed #202 .
找了一圈, 暂时没有找到没有hls而只有flv的直播间. 
如果可以请测试一下, 谢谢!
> 无hls流直播间现在会使用flv流来播放以防止读取直播流失败.

- src/BiliLite.UWP/Controls/CommentControl.xaml
- src/BiliLite.UWP/Controls/CommentControl.xaml.cs
- src/BiliLite.UWP/Models/Common/SettingConstants.cs
- src/BiliLite.UWP/Pages/SettingPage.xaml
- src/BiliLite.UWP/Pages/SettingPage.xaml.cs
- src/BiliLite.UWP/Themes/Dark.xaml
- src/BiliLite.UWP/Themes/Light.xaml
- src/BiliLite.UWP/ViewModels/Comment/CommentContentViewModel.cs
- src/BiliLite.UWP/ViewModels/Comment/CommentViewModel.cs
主要更改:
1. 注释掉了楼中楼中的"举报"按钮.
这个按钮实际上没有绑定任何功能, 在自己发的楼中楼评论中还会出现按钮重叠的问题, 因此先注释掉了.
~举报也不是好事~
2. 在评论没有图片时不会显示图片的滑条控件
大部分评论是没有图片的, 然而不管有没有图片都会有图片的滑条, 感觉既占位置又很丑, 因此加了个简单的判断在没有图片时隐藏掉了.
3. 加入了评论过长展开按钮.
解决 #150 这个需求. 
目前折叠的阈值是纯文本的75字符. 后面可以加入自定义此阈值的选项.
目前问题有: 
1. 对于不是纯文本的内容, 有可能被意外截断. ~我感觉影响不大~
2.  似乎这个展开按钮的排布还是有点丑...
本地测试暂时没有什么问题. 可以的话请多测试几次.
> 增加了评论过长折叠展开按钮以及一些其他小调整.

- src/BiliLite.UWP/Models/Requests/Api/VideoAPI.cs
- src/BiliLite.UWP/ViewModels/Video/VideoDetailPageViewModel.cs
Fixed #290 .
原因应该是默认的api返回为空，回落到了备用的api上， 
而这个api没有提供ShortLink短链接和Relates推荐视频的项。
用了一个新api,介绍在这里: https://github.com/SocialSisterYi/bilibili-API-collect/blob/c2d9291c0026350e07c01e59fc8a3ee0e0cd42f1/docs/video/recommend.md 
本地测试了 #290  中提到的两个up主，都正常。
> 修复了在某些up主的视频下无推荐视频和无法分享的错误

- src/BiliLite.UWP/Extensions/StringExtensions.cs
- src/BiliLite.UWP/Models/Common/Live/LiveAnchorProfileGloryInfo.cs
- src/BiliLite.UWP/Models/Common/UpdateJsonAddressOptions.cs
- src/BiliLite.UWP/Services/ApiHelper.cs
#378
10月19日新出的一个主播荣誉:
其中的jump_url不合法，为"/”，导致整个应用崩溃。 
现在会检测其是否为正确的url, 不正确会被替换为404页面。
> 修复点击直播中右侧主播按钮导致整个应用崩溃的问题

- src/BiliLite.UWP/Pages/SettingPage.xaml.cs
- src/BiliLite.UWP/Services/ApiHelper.cs
刚说完ghproxy稳定，他就不稳定了……全球均无法访问。
gh-proxy.com 我测试其服务器也是甲骨文韩国的，应该是同一作者。 
由于gh-proxy似乎没有捐赠地址，因此换成了其项目主页。
测试了一下，应该可以保证全国大部分地区正常获取更新文件。
> 更换了ghproxy的最新地址

- src/BiliLite.UWP/Extensions/StringExtensions.cs
"像个知道自己犯错的小孩坦然面对该有的惩罚\u0014[笑哭]"
此句评论中的控制字符导致了应用崩溃。
所以在进行必要的\r \n 替换后，将剩余的其他控制字符删除应该可以解决这个问题。
应该不会对其他视频评论区产生影响。如果有问题请修改，谢谢！
close #395
> 修复在某些视频加载评论导致应用崩溃的问题

- src/BiliLite.UWP/Extensions/StringExtensions.cs
- src/BiliLite.UWP/Models/Common/Live/DanmuMsgModel.cs
- src/BiliLite.UWP/Modules/Live/LiveMessage.cs
- src/BiliLite.UWP/Pages/LiveDetailPage.xaml
对于直播右侧弹幕栏, 更新列表:
1. 现在可以拖动宽度
2. 现在可以显示舰长类别并显示相应图片
3. 现在可以显示b站黄豆表情
4. 现在可以显示大表情（应该是任意来源的大表情，需进一步测试）
删除的内容:
1. 现在去除了用户UL等级，因为这个早就被b站弃用/半弃用了，似乎没什么用。
2. 现在去除了用户头衔，（感觉很占地方还不好看就注释掉了……，如果有需求可以直接改回来），因为似乎没什么用。
更正的内容:
现在富文本生成时的去除控制符号的正则表达式优化了一下，使得其不再匹配例如`🤓`的emoji了。
目前存在的问题:
1. 用户单独发送B站黄豆表情没有附带文本时，黄豆的显示位置会不正常的偏上。
2. ~总是感觉有点丑，元素的间距什么的需要优化 还有这个舰长的图片是很多年前的吗~
效果图:
> 直播右侧弹幕栏更新一些内容

- src/BiliLite.UWP/Models/Common/User/UserHistoryItem.cs
- src/BiliLite.UWP/Modules/User/HistoryVM.cs
- src/BiliLite.UWP/Pages/User/HistoryPage.xaml
- src/BiliLite.UWP/Pages/User/HistoryPage.xaml.cs
- src/BiliLite.UWP/ViewModels/Video/VideoDetailPageViewModel.cs
fix https://github.com/ywmoyue/biliuwp-lite/issues/400#issuecomment-1809850056
修复:
1. 历史记录页面打不开除了普通视频外的内容
2. 历史记录页面有些内容无封面
新增:
1. 历史记录现在有对应的类型和tag显示
更改:
1. 更改了历史记录页面的元素显示，效果如下(参考了看起来效果更好的 直播-关注的直播)：
> 修复并重新布局了历史记录页面

- src/BiliLite.UWP/Extensions/DynamicParseExtensions.cs
- src/BiliLite.UWP/Models/Builders/DynamicItemDisplayModelBuilder.cs
- src/BiliLite.UWP/Models/Common/Comment/CommentMemberUserSailingPendantModel.cs
- src/BiliLite.UWP/ViewModels/UserDynamic/UserDynamicViewModel.cs
对于这个UP的动态: https://space.bilibili.com/13030523/dynamic
修复以下问题: 
1. 修复其转发视频只有文字的问题。
这个问题是由于该UP主所用的转发方式和其他人不同导致的。（我没找到怎么使用这种方式）
且由于本项目所用的获取动态的api:`api.vc.bilibili.com`获取的信息不足 (如例子中, `extendJson`仅有转发的视频的av号) : 
```
"": {
"ugc": {
"ugc_id": 4772741
}
}"
```
所以修复方法就是给这类型的动态加个其转发的av号.
~（其实也有其他办法，比如直接用此av号获取视频信息再填充回卡片，就是有点……还不如直接更换现在网页端使用的`api.bilibili.com`）~
2. 修复其某个动态评论区无法加载的问题
`https://t.bilibili.com/861441728029130790` 
此评论区中某个用户的挂件(?)的id 过长，超过了Int32,产生以下错误，改成Long后正常：
```
|ERROR|3|CommentControl.GetComment|JSON integer 1699850526001 is too large or small for an Int32. Path 'data.replies[10].member.user_sailing.pendant.id', line 1, position 51007.|JSON integer 1699850526001 is too large or small for an Int32. Path 'data.replies[10].member.user_sailing.pendant.id', line 1, position 51007. 
``` …
> 修复某些UP主的动态问题

- src/BiliLite.UWP/Models/Common/Video/VideoUgcSeasonSectionEpisode.cs
- src/BiliLite.UWP/Pages/VideoDetailPage.xaml
- src/BiliLite.UWP/ViewModels/Video/VideoDetailPageViewModel.cs
fix #419 
本问题主要是因为在二维码登录的情况下，视频详情的api `https://app.bilibili.com/x/v2/view` 拿到的`ugc_season`为`null`导致的。 
暂时不知道是b站官方的api弃用还是什么问题。
使用了web版的api数据填充了，目前除了播放列表除了没有每集的作者名称（感觉并不太重要）外是可用的。
目前我使用ipad抓包, app端的视频详情api已经换成了grpc `/bilibili.app.view.v1.View/View`. 如果您有时间的话还是希望给这里换成grpc! @ywmoyue
> 修复二维码登录下无播放列表的问题

- src/BiliLite.UWP/BiliLite.UWP.csproj
- src/BiliLite.UWP/Models/Common/Live/DefaultPlayUrlSourceOptions.cs
- src/BiliLite.UWP/Models/Common/Live/LiveMessageHandleActionsMap.cs
- src/BiliLite.UWP/Models/Common/SettingConstants.cs
- src/BiliLite.UWP/Pages/LiveDetailPage.xaml
- src/BiliLite.UWP/Pages/LiveDetailPage.xaml.cs
- src/BiliLite.UWP/ViewModels/Live/LiveDetailPageViewModel.cs
- src/BiliLite.UWP/ViewModels/Live/LiveRoomLotteryViewModel.cs
1. 修复天选时刻错误的展示`发送弹幕`按钮和`中奖名单`的问题
2. 修复新一轮天选时刻/人气红包开始时倒计时展示的问题
3. 修复人气红包图片没有正确的被加入csproj的问题
4. 更改了一下金银瓜子的显示位置
5. 新增默认直播流选择
目前我这里遇到的有三种： 
- mcdn,疑似来自京东云的pcdn
- b站自建cdn,基本在每个省份都有服务器
- 第三方和备用cdn,主要用于海外和备用
其中, b站默认的mcdn在我这里及其不稳定，时不时就会卡住，换用其他源后有好转。
故此加入了用简单的字符串匹配选择默认直播流的功能。
但是，在同一界面下的两个ComboBox`播放器默认模式`和`直播流默认来源`还是会有显示bug,目前未找到修复方法。
> 直播间bug修复以及新增默认直播流选择

- src/BiliLite.UWP/BiliLite.UWP.csproj
- src/BiliLite.UWP/Extensions/ViewModelExtensions.cs
- src/BiliLite.UWP/Models/Common/User/SubmitCollectionItemModel.cs
- src/BiliLite.UWP/Models/Requests/Api/User/UserDetailAPI.cs
- src/BiliLite.UWP/Modules/User/UserDetail/UserDetailVM.cs
- src/BiliLite.UWP/Pages/UserInfoPage.xaml
- src/BiliLite.UWP/Pages/UserInfoPage.xaml.cs
- src/BiliLite.UWP/Services/MessageCenter.cs
- src/BiliLite.UWP/ViewModels/User/UserSubmitCollectionViewModel.cs
close #438
为个人主页添加了合集选项，效果如下：
另外还调整了一些外观方面的参数
仍有少许问题。 如直播回放，其从api获取的类似于`bilibili://music/playlist/playpage/2484684`, 现在不可被程序正确解析。
因此先调用WebPage作为临时方案。
该格式为一播放列表，在ipad端点击时会将尾部的数字id进行一个额外的api请求：`GET api.bilibili.com/x/v2/medialist/resource/list`并将id传入，返回类似于`翻页式`的这个播放列表的各个视频信息。可能需要重新设计视频界面来适配这一播放列表形式。
> 为个人主页添加了合集选项.

- src/BiliLite.UWP/Converters/ImageCompressionConvert.cs
- src/BiliLite.UWP/Models/Requests/Api/Home/LiveAPI.cs
- src/BiliLite.UWP/Modules/Home/LiveVM.cs
- src/BiliLite.UWP/Pages/Home/LivePage.xaml
- src/BiliLite.UWP/Pages/Live/LiveAreaPage.xaml
使用`mobi_app=android`替换掉iphone后可以正常获取直播分区选项。
同时, fix #446 , 问题原因是`娱乐 - 全部娱乐`的`pic`为空导致的。
使用`imageConvert`的功能修复。同时使其更改为请求`.png`
为了使加载的图片被本地缩放导致难看的颗粒感出现加上了两倍于图片宽的请求参数，这样就不糊也不颗粒了。 
更改了直播二级分区的图片大小。现在图片差不多和四个字一样宽了。
> 修复直播分区相关问题

- src/BiliLite.UWP/Pages/LiveDetailPage.xaml.cs
- src/BiliLite.UWP/Player/SubPlayers/LiveHlsPlayer.cs
有时flv的路线选项和hls的不一样多。这样会导致例如`Flv 线路三`无法播放，因为根本没有这个源。
调整了路线选择时的检测，在发现这个路线没有这个源时会调用对方的源播放。
> 修复直播间的一个线路选择问题

- src/BiliLite.UWP/BiliLite.UWP.csproj
- src/BiliLite.UWP/Models/Exceptions/NotFoundException.cs
- src/BiliLite.UWP/Services/GrpcService.cs
- src/BiliLite.UWP/ViewModels/User/UserSubmitVideoViewModel.cs
fix #426 
搜索关键字不存在于up主上传的视频列表导致的。
调整的可能有点问题，如果不行请修改。
> 修改了个人主页搜索视频为空时的报错反馈

- src/BiliLite.UWP/Controls/Player.xaml.cs
- src/BiliLite.UWP/Controls/PlayerControl.xaml
- src/BiliLite.UWP/Controls/PlayerControl.xaml.cs
- src/BiliLite.UWP/Player/IBiliPlayer.cs
为画面尺寸添加了兼容模式选项，兼容模式下会在使用Stretch.Fill方法的同时通过计算缩放比例实现正常的尺寸显示。经测试可以修复部分设备使用默认模式的Stretch.Uniform方法导致缩放窗口画面黑屏的问题。此外，测试还发现此模式下播放时窗口缩放性能比默认更好
> 画面尺寸添加兼容模式，修复部分设备缩放画面黑屏的问题

- src/BiliLite.UWP/Models/Requests/Api/Home/HotApi.cs
- src/BiliLite.UWP/Pages/Home/HotPage.xaml
> 修复热门页错误，调整元素布局

- src/BiliLite.UWP/Modules/Live/LiveMessage.cs
现在会使用前一波到这一波的延迟与本波弹幕个数综合判断需要的延迟。
在几个大型直播间试了一下，效果良好，没有延迟。
图为配合寒霜弹幕使的效果
fix #613
> 修复直播弹幕延迟问题

- src/BiliLite.UWP/Extensions/StringExtensions.cs
某些评论中发送了大量的bv号，但是只有其中的部分被解析成了可点击的按钮。 
修复了该问题。
> 修复在bv号大量堆积情况下不能正确转换为按钮的问题

- src/BiliLite.UWP/BiliLite.UWP.csproj
每次来回切换分支我都需要配置正确的sdk及证书#924 ，因此为了便于维护，提前将sdk统一为19041
未来将有两个长期性RP保持更新，一个涉及主题颜色，一个涉及圆角化ui
> 更新sdk19041

- src/BiliLite.UWP/BiliLite.UWP.csproj
- src/BiliLite.UWP/Extensions/TimeExtensions.cs
- src/BiliLite.UWP/Models/Common/Enumerates.cs
- src/BiliLite.UWP/Models/Common/Live/LiveMessageHandleActionsMap.cs
- src/BiliLite.UWP/Models/Common/Live/LiveRoomEmoticon.cs
- src/BiliLite.UWP/Models/Requests/Api/Live/LiveRoomAPI.cs
- src/BiliLite.UWP/Modules/Live/LiveMessage.cs
- src/BiliLite.UWP/Pages/LiveDetailPage.xaml
- src/BiliLite.UWP/Pages/LiveDetailPage.xaml.cs
- src/BiliLite.UWP/ViewModels/Live/LiveRoomViewModel.cs
**🎄圣诞快乐~**
- **加入了当前房间在线人数显示**
由于b站信息流的特性，现在可以与之前的看过人数轮换显示于粉丝数旁
- **加入全屏/大屏幕模式下的弹幕输入框**
- **支持发送表情，包括可混杂于普通文本中的黄豆表情与单独发送的大表情**
- **直播间加载速度优化，优先加载视频流和弹幕流**
- **解决之前的有新舰长但PivotHeader上的舰长数不更新的问题**
原因是当没有选择大航海页时, UI选择懒加载导致只有选择到大航海页才会更新
解决方案就是有新舰长时闪现加载一下大航海页…… 有更好的办法欢迎提出
- **一些其他的外观与Typo优化**
fix #949
> 圣诞更新（直播间优化）

- src/BiliLite.UWP/Converters/ColorConvert.cs
需要判断是否会出现带#前缀的非法参数，如#123f567
#1068
> 沿用旧方法解析不带#前缀的颜色代码

- src/BiliLite.UWP/Controls/DataTemplateSelectors/UserDynamicItemV2DataTemplateSelector.cs
b站api现在会将纯文字动态的动态类型改为"DRAW"而不是之前的"WORD"。 而：
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/dynamic/dynamic_enum.md
中说"DRAW"类型应该是带图的文字动态，但这压根没图，只能说是b站抽风了。
fix #1146
> 修复纯文字动态无法显示的问题

- src/BiliLite.UWP/BiliLite.UWP.csproj
- src/BiliLite.UWP/Controls/PlayerControl.xaml
- src/BiliLite.UWP/Controls/PlayerControl.xaml.cs
- src/BiliLite.UWP/Controls/PlayerToast.xaml
- src/BiliLite.UWP/Controls/PlayerToast.xaml.cs
- src/BiliLite.UWP/Controls/Settings/PlaySettingsControl.xaml
- src/BiliLite.UWP/Controls/Settings/PlaySettingsControl.xaml.cs
- src/BiliLite.UWP/Converters/TimeSpanStrFormatConverter.cs
- src/BiliLite.UWP/Models/Common/Enumerates.cs
- src/BiliLite.UWP/Models/Common/Player/PlayerSkipItem.cs
- src/BiliLite.UWP/Models/Common/SettingConstants.cs
- src/BiliLite.UWP/Models/Common/Video/PlayInfo.cs
- src/BiliLite.UWP/Models/Requests/Api/SponsorBlockApi.cs
- src/BiliLite.UWP/Pages/VideoDetailPage.xaml.cs
- src/BiliLite.UWP/Services/ApiHelper.cs
- src/BiliLite.UWP/Services/PlayerToastService.cs
- src/BiliLite.UWP/Styles/Converter.xaml
- src/BiliLite.UWP/ViewModels/PlayControlViewModel.cs
- src/BiliLite.UWP/ViewModels/PlayerToastViewModel.cs
- src/BiliLite.UWP/ViewModels/Video/SponsorBlockViewModel.cs
- src/BiliLite.UWP/ViewModels/Video/VideoDetailPageViewModel.cs
完成了Sponsor部分核心功能。
未能做到的：
以上的未完成功能的开发优先级依次递减。 
尤其是进度条着色，是向服务器提交片段的基础。
@ywmoyue 您有时间的话可以看一下这个功能怎么实现。感谢！
另外，发现如果将片段起点定为0，会引起播放器报错；
片段结尾定为视频终点，会卡死播放器一段时间。
希望可以检查一下这两个问题是什么问题引起的。
close #874
> 初步加入SponsorBlock功能
